name: dsbox-cleaner-env
dependencies:
- pip=9.0.1
- python=3.6.2
- scipy>=0.19.0
- pip:
  - numpy>=1.11.1
  - pandas>=0.20.1
  - langdetect>=1.0.7
  - scikit-learn>=0.18.0
  - python-dateutil>=2.5.2
  - six>=1.10.0
  - fancyimpute
  - dsbox-datapreprocessing
  - stopit
  - tzlocal==1.5.1
  - pytz==2018.3
